#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Murakami.Resource", IsApplication=true)]

namespace Murakami
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_text_dark = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int common_google_signin_btn_text_light = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int common_plus_signin_btn_text_dark = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int common_plus_signin_btn_text_light = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_murakami_v5_menu_chain1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int California = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cart = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cart2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_full_open_on_phone = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_dark_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_disabled = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_focused = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_normal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_light_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_ic_googleplayservices = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_dark_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_dark_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_light_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_light_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_light_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_dark_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_dark_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_dark_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light_disabled = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_light_focused = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_light_normal = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_light_pressed = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int deserts = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int dobavitvorz = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int dostavkaicon = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Drakoni = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int facebook = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Filadelfia = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int goryachi = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int GoryachieRolli = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int header5 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int holodnizakuski = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ico_pro_nas = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Icon = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int inst = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int lanchi = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int logo_murakami = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int lokshina = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Maki = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int menu = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int minus = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int napitki = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int novosti_ico = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int osnovni = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int plus = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int rise = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int rolli = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int salads = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int sashimi = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int seti = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int smotret_na_karte = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int souces = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int soupes = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int spisok = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int sushi = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int sushidetail = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int sushidetail2 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int sushiicon = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int tepan = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int twitter = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int vk = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int zakuski = 2130837590;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002e
			public const int add = 2131165230;
			
			// aapt resource value: 0x7f070034
			public const int add1 = 2131165236;
			
			// aapt resource value: 0x7f070067
			public const int add10 = 2131165287;
			
			// aapt resource value: 0x7f07006c
			public const int add11 = 2131165292;
			
			// aapt resource value: 0x7f070071
			public const int add12 = 2131165297;
			
			// aapt resource value: 0x7f070076
			public const int add13 = 2131165302;
			
			// aapt resource value: 0x7f0700ae
			public const int add14 = 2131165358;
			
			// aapt resource value: 0x7f0700b3
			public const int add15 = 2131165363;
			
			// aapt resource value: 0x7f0700c6
			public const int add16 = 2131165382;
			
			// aapt resource value: 0x7f070038
			public const int add2 = 2131165240;
			
			// aapt resource value: 0x7f07003c
			public const int add3 = 2131165244;
			
			// aapt resource value: 0x7f070040
			public const int add4 = 2131165248;
			
			// aapt resource value: 0x7f070044
			public const int add5 = 2131165252;
			
			// aapt resource value: 0x7f070049
			public const int add6 = 2131165257;
			
			// aapt resource value: 0x7f070058
			public const int add7 = 2131165272;
			
			// aapt resource value: 0x7f07005d
			public const int add8 = 2131165277;
			
			// aapt resource value: 0x7f070062
			public const int add9 = 2131165282;
			
			// aapt resource value: 0x7f070005
			public const int adjust_height = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int adjust_width = 2131165190;
			
			// aapt resource value: 0x7f070084
			public const int akcii = 2131165316;
			
			// aapt resource value: 0x7f0700ba
			public const int app_murakami_v5_menu_chain1 = 2131165370;
			
			// aapt resource value: 0x7f07000a
			public const int auto = 2131165194;
			
			// aapt resource value: 0x7f070082
			public const int bludoDnia = 2131165314;
			
			// aapt resource value: 0x7f0700a1
			public const int california = 2131165345;
			
			// aapt resource value: 0x7f07007f
			public const int cart = 2131165311;
			
			// aapt resource value: 0x7f070012
			public const int cartButton = 2131165202;
			
			// aapt resource value: 0x7f07000b
			public const int dark = 2131165195;
			
			// aapt resource value: 0x7f070090
			public const int deserts = 2131165328;
			
			// aapt resource value: 0x7f070054
			public const int discription = 2131165268;
			
			// aapt resource value: 0x7f070083
			public const int dostavka = 2131165315;
			
			// aapt resource value: 0x7f0700a2
			public const int drakoni = 2131165346;
			
			// aapt resource value: 0x7f07008e
			public const int facebook = 2131165326;
			
			// aapt resource value: 0x7f0700a3
			public const int filadelfia = 2131165347;
			
			// aapt resource value: 0x7f07009e
			public const int goryachi = 2131165342;
			
			// aapt resource value: 0x7f0700a4
			public const int goryachierolli = 2131165348;
			
			// aapt resource value: 0x7f0700a5
			public const int holodnizakuski = 2131165349;
			
			// aapt resource value: 0x7f070000
			public const int hybrid = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int ico_pro_nas = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int icon_only = 2131165191;
			
			// aapt resource value: 0x7f07001b
			public const int image = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int image1 = 2131165214;
			
			// aapt resource value: 0x7f070065
			public const int image10 = 2131165285;
			
			// aapt resource value: 0x7f07006a
			public const int image11 = 2131165290;
			
			// aapt resource value: 0x7f07006f
			public const int image12 = 2131165295;
			
			// aapt resource value: 0x7f070074
			public const int image13 = 2131165300;
			
			// aapt resource value: 0x7f0700ac
			public const int image14 = 2131165356;
			
			// aapt resource value: 0x7f0700b1
			public const int image15 = 2131165361;
			
			// aapt resource value: 0x7f0700c4
			public const int image16 = 2131165380;
			
			// aapt resource value: 0x7f070020
			public const int image2 = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int image3 = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int image4 = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int image5 = 2131165222;
			
			// aapt resource value: 0x7f070047
			public const int image6 = 2131165255;
			
			// aapt resource value: 0x7f070056
			public const int image7 = 2131165270;
			
			// aapt resource value: 0x7f07005b
			public const int image8 = 2131165275;
			
			// aapt resource value: 0x7f070060
			public const int image9 = 2131165280;
			
			// aapt resource value: 0x7f070028
			public const int imageButton4 = 2131165224;
			
			// aapt resource value: 0x7f0700c2
			public const int imageView1 = 2131165378;
			
			// aapt resource value: 0x7f07008f
			public const int instagram = 2131165327;
			
			// aapt resource value: 0x7f0700a0
			public const int lanchi = 2131165344;
			
			// aapt resource value: 0x7f07000c
			public const int light = 2131165196;
			
			// aapt resource value: 0x7f07007a
			public const int linearLayout1 = 2131165306;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout10 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout11 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int linearLayout12 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout13 = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int linearLayout14 = 2131165213;
			
			// aapt resource value: 0x7f070029
			public const int linearLayout15 = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int linearLayout16 = 2131165227;
			
			// aapt resource value: 0x7f070031
			public const int linearLayout17 = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int linearLayout18 = 2131165234;
			
			// aapt resource value: 0x7f07004d
			public const int linearLayout19 = 2131165261;
			
			// aapt resource value: 0x7f07008b
			public const int linearLayout2 = 2131165323;
			
			// aapt resource value: 0x7f07004e
			public const int linearLayout20 = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int linearLayout21 = 2131165263;
			
			// aapt resource value: 0x7f070094
			public const int linearLayout213 = 2131165332;
			
			// aapt resource value: 0x7f070053
			public const int linearLayout22 = 2131165267;
			
			// aapt resource value: 0x7f070096
			public const int linearLayout223 = 2131165334;
			
			// aapt resource value: 0x7f07002f
			public const int linearLayout23 = 2131165231;
			
			// aapt resource value: 0x7f070092
			public const int linearLayout283 = 2131165330;
			
			// aapt resource value: 0x7f070079
			public const int linearLayout3 = 2131165305;
			
			// aapt resource value: 0x7f07007b
			public const int linearLayout4 = 2131165307;
			
			// aapt resource value: 0x7f07007c
			public const int linearLayout5 = 2131165308;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout6 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout7 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout8 = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int linearLayout9 = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int logoButton = 2131165201;
			
			// aapt resource value: 0x7f07007e
			public const int logo_murakami = 2131165310;
			
			// aapt resource value: 0x7f07009a
			public const int lokshina = 2131165338;
			
			// aapt resource value: 0x7f0700a6
			public const int maki = 2131165350;
			
			// aapt resource value: 0x7f070081
			public const int map = 2131165313;
			
			// aapt resource value: 0x7f07007d
			public const int menu = 2131165309;
			
			// aapt resource value: 0x7f070010
			public const int menuButton = 2131165200;
			
			// aapt resource value: 0x7f070050
			public const int minus = 2131165264;
			
			// aapt resource value: 0x7f07001c
			public const int name = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int name1 = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int name2 = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int name3 = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int name4 = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int name5 = 2131165223;
			
			// aapt resource value: 0x7f0700aa
			public const int name6 = 2131165354;
			
			// aapt resource value: 0x7f0700ab
			public const int name7 = 2131165355;
			
			// aapt resource value: 0x7f07009d
			public const int napoi = 2131165341;
			
			// aapt resource value: 0x7f070001
			public const int none = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int normal = 2131165186;
			
			// aapt resource value: 0x7f070085
			public const int novosti = 2131165317;
			
			// aapt resource value: 0x7f0700a7
			public const int osnovni = 2131165351;
			
			// aapt resource value: 0x7f070052
			public const int plus = 2131165266;
			
			// aapt resource value: 0x7f07002a
			public const int posttitle = 2131165226;
			
			// aapt resource value: 0x7f070033
			public const int posttitle1 = 2131165235;
			
			// aapt resource value: 0x7f070066
			public const int posttitle10 = 2131165286;
			
			// aapt resource value: 0x7f07006b
			public const int posttitle11 = 2131165291;
			
			// aapt resource value: 0x7f070070
			public const int posttitle12 = 2131165296;
			
			// aapt resource value: 0x7f070075
			public const int posttitle13 = 2131165301;
			
			// aapt resource value: 0x7f0700ad
			public const int posttitle14 = 2131165357;
			
			// aapt resource value: 0x7f0700b2
			public const int posttitle15 = 2131165362;
			
			// aapt resource value: 0x7f0700c5
			public const int posttitle16 = 2131165381;
			
			// aapt resource value: 0x7f070037
			public const int posttitle2 = 2131165239;
			
			// aapt resource value: 0x7f07003b
			public const int posttitle3 = 2131165243;
			
			// aapt resource value: 0x7f07003f
			public const int posttitle4 = 2131165247;
			
			// aapt resource value: 0x7f070043
			public const int posttitle5 = 2131165251;
			
			// aapt resource value: 0x7f070048
			public const int posttitle6 = 2131165256;
			
			// aapt resource value: 0x7f070057
			public const int posttitle7 = 2131165271;
			
			// aapt resource value: 0x7f07005c
			public const int posttitle8 = 2131165276;
			
			// aapt resource value: 0x7f070061
			public const int posttitle9 = 2131165281;
			
			// aapt resource value: 0x7f070030
			public const int posttittle = 2131165232;
			
			// aapt resource value: 0x7f07002c
			public const int price = 2131165228;
			
			// aapt resource value: 0x7f070035
			public const int price1 = 2131165237;
			
			// aapt resource value: 0x7f070068
			public const int price10 = 2131165288;
			
			// aapt resource value: 0x7f07006d
			public const int price11 = 2131165293;
			
			// aapt resource value: 0x7f070072
			public const int price12 = 2131165298;
			
			// aapt resource value: 0x7f070077
			public const int price13 = 2131165303;
			
			// aapt resource value: 0x7f0700af
			public const int price14 = 2131165359;
			
			// aapt resource value: 0x7f0700b4
			public const int price15 = 2131165364;
			
			// aapt resource value: 0x7f0700c7
			public const int price16 = 2131165383;
			
			// aapt resource value: 0x7f070039
			public const int price2 = 2131165241;
			
			// aapt resource value: 0x7f07003d
			public const int price3 = 2131165245;
			
			// aapt resource value: 0x7f070041
			public const int price4 = 2131165249;
			
			// aapt resource value: 0x7f070045
			public const int price5 = 2131165253;
			
			// aapt resource value: 0x7f07004a
			public const int price6 = 2131165258;
			
			// aapt resource value: 0x7f070059
			public const int price7 = 2131165273;
			
			// aapt resource value: 0x7f07005e
			public const int price8 = 2131165278;
			
			// aapt resource value: 0x7f070063
			public const int price9 = 2131165283;
			
			// aapt resource value: 0x7f070087
			public const int proMurkami = 2131165319;
			
			// aapt resource value: 0x7f0700c3
			public const int progressBar1 = 2131165379;
			
			// aapt resource value: 0x7f070051
			public const int quantity = 2131165265;
			
			// aapt resource value: 0x7f070086
			public const int restorani = 2131165318;
			
			// aapt resource value: 0x7f0700a8
			public const int rise = 2131165352;
			
			// aapt resource value: 0x7f070091
			public const int rolli = 2131165329;
			
			// aapt resource value: 0x7f070097
			public const int salads = 2131165335;
			
			// aapt resource value: 0x7f07009f
			public const int sashimi = 2131165343;
			
			// aapt resource value: 0x7f070003
			public const int satellite = 2131165187;
			
			// aapt resource value: 0x7f070016
			public const int scrollView1 = 2131165206;
			
			// aapt resource value: 0x7f07004c
			public const int scrollView2 = 2131165260;
			
			// aapt resource value: 0x7f070093
			public const int seti = 2131165331;
			
			// aapt resource value: 0x7f0700bb
			public const int smotret_na_karte = 2131165371;
			
			// aapt resource value: 0x7f070098
			public const int souces = 2131165336;
			
			// aapt resource value: 0x7f070099
			public const int soupes = 2131165337;
			
			// aapt resource value: 0x7f070080
			public const int spisok = 2131165312;
			
			// aapt resource value: 0x7f070008
			public const int standard = 2131165192;
			
			// aapt resource value: 0x7f070095
			public const int sushi = 2131165333;
			
			// aapt resource value: 0x7f0700a9
			public const int sushidetail = 2131165353;
			
			// aapt resource value: 0x7f070088
			public const int tel = 2131165320;
			
			// aapt resource value: 0x7f07009b
			public const int tepan = 2131165339;
			
			// aapt resource value: 0x7f070004
			public const int terrain = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int textView1 = 2131165205;
			
			// aapt resource value: 0x7f0700bc
			public const int textView10 = 2131165372;
			
			// aapt resource value: 0x7f0700bd
			public const int textView11 = 2131165373;
			
			// aapt resource value: 0x7f0700bf
			public const int textView12 = 2131165375;
			
			// aapt resource value: 0x7f0700c1
			public const int textView13 = 2131165377;
			
			// aapt resource value: 0x7f070089
			public const int textView2 = 2131165321;
			
			// aapt resource value: 0x7f07008a
			public const int textView3 = 2131165322;
			
			// aapt resource value: 0x7f0700b6
			public const int textView4 = 2131165366;
			
			// aapt resource value: 0x7f0700b7
			public const int textView5 = 2131165367;
			
			// aapt resource value: 0x7f0700b8
			public const int textView6 = 2131165368;
			
			// aapt resource value: 0x7f0700b9
			public const int textView7 = 2131165369;
			
			// aapt resource value: 0x7f0700be
			public const int textView8 = 2131165374;
			
			// aapt resource value: 0x7f0700c0
			public const int textView9 = 2131165376;
			
			// aapt resource value: 0x7f07008d
			public const int twitter = 2131165325;
			
			// aapt resource value: 0x7f07008c
			public const int vk = 2131165324;
			
			// aapt resource value: 0x7f07002d
			public const int weight = 2131165229;
			
			// aapt resource value: 0x7f070036
			public const int weight1 = 2131165238;
			
			// aapt resource value: 0x7f070069
			public const int weight10 = 2131165289;
			
			// aapt resource value: 0x7f07006e
			public const int weight11 = 2131165294;
			
			// aapt resource value: 0x7f070073
			public const int weight12 = 2131165299;
			
			// aapt resource value: 0x7f070078
			public const int weight13 = 2131165304;
			
			// aapt resource value: 0x7f0700b0
			public const int weight14 = 2131165360;
			
			// aapt resource value: 0x7f0700b5
			public const int weight15 = 2131165365;
			
			// aapt resource value: 0x7f0700c8
			public const int weight16 = 2131165384;
			
			// aapt resource value: 0x7f07003a
			public const int weight2 = 2131165242;
			
			// aapt resource value: 0x7f07003e
			public const int weight3 = 2131165246;
			
			// aapt resource value: 0x7f070042
			public const int weight4 = 2131165250;
			
			// aapt resource value: 0x7f070046
			public const int weight5 = 2131165254;
			
			// aapt resource value: 0x7f07004b
			public const int weight6 = 2131165259;
			
			// aapt resource value: 0x7f07005a
			public const int weight7 = 2131165274;
			
			// aapt resource value: 0x7f07005f
			public const int weight8 = 2131165279;
			
			// aapt resource value: 0x7f070064
			public const int weight9 = 2131165284;
			
			// aapt resource value: 0x7f070009
			public const int wide = 2131165193;
			
			// aapt resource value: 0x7f070055
			public const int zakazat = 2131165269;
			
			// aapt resource value: 0x7f07009c
			public const int zakuski = 2131165340;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Akcii = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BludoDnia = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BludoDnya = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int California = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int deserts = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int detalniyProsmotr = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int drakoni = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Filadelfia = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int GoryachieRolli = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int InshiRolli = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int karta = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Lanchi = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Lapsha = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Main = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Maki = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Menu = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Napitki = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Novosti = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int OsnovniBluda = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ProMurkami = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Salads = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Sashimi = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int SetRestoranov = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Sets = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Souces = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Soupes = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Splash = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Sushi = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Tepan = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Zakuski = 2130903069;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040020
			public const int ApplicationName = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int Hello = 2130968607;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
